import type { EconNode, EconEdge, WorldRegion } from '@econview/shared'

// ── Country → Region mapping ────────────────────────────────────────────────────

export const COUNTRY_REGIONS: Record<string, WorldRegion> = {
  USA: 'north_america', CAN: 'north_america', MEX: 'north_america',
  BRA: 'latin_america', ARG: 'latin_america', CHL: 'latin_america', COL: 'latin_america', PER: 'latin_america',
  GBR: 'western_europe', DEU: 'western_europe', FRA: 'western_europe', ITA: 'western_europe', ESP: 'western_europe',
  NLD: 'western_europe', CHE: 'western_europe', BEL: 'western_europe', SWE: 'western_europe', NOR: 'western_europe',
  AUT: 'western_europe', DNK: 'western_europe', FIN: 'western_europe', IRL: 'western_europe', PRT: 'western_europe',
  RUS: 'eastern_europe', POL: 'eastern_europe', TUR: 'eastern_europe', CZE: 'eastern_europe', KAZ: 'eastern_europe',
  SAU: 'middle_east', ARE: 'middle_east', ISR: 'middle_east', QAT: 'middle_east', EGY: 'middle_east',
  NGA: 'africa', ZAF: 'africa',
  IND: 'south_asia', PAK: 'south_asia', BGD: 'south_asia',
  CHN: 'east_asia', JPN: 'east_asia', KOR: 'east_asia', HKG: 'east_asia', TWN: 'east_asia',
  IDN: 'southeast_asia', THA: 'southeast_asia', SGP: 'southeast_asia', PHL: 'southeast_asia', MYS: 'southeast_asia', VNM: 'southeast_asia',
  AUS: 'oceania', NZL: 'oceania',
}

// ── Country currency codes ───────────────────────────────────────────────────

export const COUNTRY_CURRENCIES: Record<string, string> = {
  USA: 'USD', CAN: 'CAD', MEX: 'MXN', BRA: 'BRL', ARG: 'ARS', CHL: 'CLP', COL: 'COP', PER: 'PEN',
  GBR: 'GBP', DEU: 'EUR', FRA: 'EUR', ITA: 'EUR', ESP: 'EUR', NLD: 'EUR', BEL: 'EUR', AUT: 'EUR',
  IRL: 'EUR', PRT: 'EUR', FIN: 'EUR', CHE: 'CHF', SWE: 'SEK', NOR: 'NOK', DNK: 'DKK',
  RUS: 'RUB', POL: 'PLN', TUR: 'TRY', CZE: 'CZK', KAZ: 'KZT',
  SAU: 'SAR', ARE: 'AED', ISR: 'ILS', QAT: 'QAR', EGY: 'EGP',
  NGA: 'NGN', ZAF: 'ZAR',
  IND: 'INR', PAK: 'PKR', BGD: 'BDT',
  CHN: 'CNY', JPN: 'JPY', KOR: 'KRW', HKG: 'HKD', TWN: 'TWD',
  IDN: 'IDR', THA: 'THB', SGP: 'SGD', PHL: 'PHP', MYS: 'MYR', VNM: 'VND',
  AUS: 'AUD', NZL: 'NZD',
}

// ── 50+ Major Economies ──────────────────────────────────────────────────────

export const MOCK_COUNTRIES: EconNode[] = [
  { id: 'USA', type: 'country', label: 'United States', countryCode: 'USA', gdp: 27360e9, gdpGrowth: 2.5, population: 334e6, region: 'north_america', currency: 'USD', inflation: 3.1, unemployment: 3.7, debtToGdp: 123, interestRate: 4.33, creditRating: 'AAA' },
  { id: 'CHN', type: 'country', label: 'China', countryCode: 'CHN', gdp: 17795e9, gdpGrowth: 5.2, population: 1412e6, region: 'east_asia', currency: 'CNY', inflation: 0.7, unemployment: 5.2, debtToGdp: 83, interestRate: 3.45, creditRating: 'A+' },
  { id: 'DEU', type: 'country', label: 'Germany', countryCode: 'DEU', gdp: 4456e9, gdpGrowth: -0.3, population: 84e6, region: 'western_europe', currency: 'EUR', inflation: 2.9, unemployment: 5.9, debtToGdp: 64, interestRate: 4.00, creditRating: 'AAA' },
  { id: 'JPN', type: 'country', label: 'Japan', countryCode: 'JPN', gdp: 4213e9, gdpGrowth: 1.9, population: 124e6, region: 'east_asia', currency: 'JPY', inflation: 2.2, unemployment: 2.5, debtToGdp: 255, interestRate: -0.10, creditRating: 'A+' },
  { id: 'IND', type: 'country', label: 'India', countryCode: 'IND', gdp: 3730e9, gdpGrowth: 7.8, population: 1428e6, region: 'south_se_asia', currency: 'INR', inflation: 5.1, unemployment: 7.0, debtToGdp: 81, interestRate: 6.50, creditRating: 'BBB-' },
  { id: 'GBR', type: 'country', label: 'United Kingdom', countryCode: 'GBR', gdp: 3332e9, gdpGrowth: 0.1, population: 67e6, region: 'western_europe', currency: 'GBP', inflation: 4.0, unemployment: 4.2, debtToGdp: 101, interestRate: 5.25, creditRating: 'AA' },
  { id: 'FRA', type: 'country', label: 'France', countryCode: 'FRA', gdp: 3031e9, gdpGrowth: 0.7, population: 68e6, region: 'western_europe', currency: 'EUR', inflation: 2.4, unemployment: 7.3, debtToGdp: 112, interestRate: 4.00, creditRating: 'AA-' },
  { id: 'ITA', type: 'country', label: 'Italy', countryCode: 'ITA', gdp: 2255e9, gdpGrowth: 0.7, population: 59e6, region: 'western_europe', currency: 'EUR', inflation: 1.0, unemployment: 7.2, debtToGdp: 140, interestRate: 4.00, creditRating: 'BBB' },
  { id: 'BRA', type: 'country', label: 'Brazil', countryCode: 'BRA', gdp: 2174e9, gdpGrowth: 2.9, population: 216e6, region: 'latin_america', currency: 'BRL', inflation: 4.5, unemployment: 7.8, debtToGdp: 74, interestRate: 11.25, creditRating: 'BB' },
  { id: 'CAN', type: 'country', label: 'Canada', countryCode: 'CAN', gdp: 2140e9, gdpGrowth: 1.1, population: 40e6, region: 'north_america', currency: 'CAD', inflation: 3.4, unemployment: 5.8, debtToGdp: 107, interestRate: 4.50, creditRating: 'AAA' },
  { id: 'RUS', type: 'country', label: 'Russia', countryCode: 'RUS', gdp: 1993e9, gdpGrowth: 3.6, population: 144e6, region: 'eastern_europe', currency: 'RUB', inflation: 7.4, unemployment: 3.0, debtToGdp: 20, interestRate: 16.00, creditRating: 'NR' },
  { id: 'KOR', type: 'country', label: 'South Korea', countryCode: 'KOR', gdp: 1713e9, gdpGrowth: 1.4, population: 52e6, region: 'east_asia', currency: 'KRW', inflation: 3.2, unemployment: 2.8, debtToGdp: 54, interestRate: 3.50, creditRating: 'AA' },
  { id: 'AUS', type: 'country', label: 'Australia', countryCode: 'AUS', gdp: 1688e9, gdpGrowth: 2.0, population: 26e6, region: 'oceania', currency: 'AUD', inflation: 3.4, unemployment: 3.9, debtToGdp: 52, interestRate: 4.35, creditRating: 'AAA' },
  { id: 'MEX', type: 'country', label: 'Mexico', countryCode: 'MEX', gdp: 1789e9, gdpGrowth: 3.2, population: 130e6, region: 'latin_america', currency: 'MXN', inflation: 4.7, unemployment: 2.8, debtToGdp: 50, interestRate: 11.25, creditRating: 'BBB' },
  { id: 'ESP', type: 'country', label: 'Spain', countryCode: 'ESP', gdp: 1582e9, gdpGrowth: 2.5, population: 48e6, region: 'western_europe', currency: 'EUR', inflation: 3.3, unemployment: 11.7, debtToGdp: 107, interestRate: 4.00, creditRating: 'A' },
  { id: 'IDN', type: 'country', label: 'Indonesia', countryCode: 'IDN', gdp: 1417e9, gdpGrowth: 5.1, population: 277e6, region: 'south_se_asia', currency: 'IDR', inflation: 2.6, unemployment: 5.3, debtToGdp: 39, interestRate: 6.00, creditRating: 'BBB' },
  { id: 'NLD', type: 'country', label: 'Netherlands', countryCode: 'NLD', gdp: 1093e9, gdpGrowth: 0.1, population: 18e6, region: 'western_europe', currency: 'EUR', inflation: 1.2, unemployment: 3.6, debtToGdp: 48, interestRate: 4.00, creditRating: 'AAA' },
  { id: 'SAU', type: 'country', label: 'Saudi Arabia', countryCode: 'SAU', gdp: 1069e9, gdpGrowth: -0.8, population: 36e6, region: 'middle_east', currency: 'SAR', inflation: 1.6, unemployment: 4.8, debtToGdp: 26, interestRate: 6.00, creditRating: 'A' },
  { id: 'TUR', type: 'country', label: 'Turkey', countryCode: 'TUR', gdp: 1108e9, gdpGrowth: 4.5, population: 85e6, region: 'eastern_europe', currency: 'TRY', inflation: 61.5, unemployment: 9.4, debtToGdp: 35, interestRate: 45.00, creditRating: 'B+' },
  { id: 'CHE', type: 'country', label: 'Switzerland', countryCode: 'CHE', gdp: 906e9, gdpGrowth: 0.7, population: 9e6, region: 'western_europe', currency: 'CHF', inflation: 1.7, unemployment: 2.3, debtToGdp: 38, interestRate: 1.75, creditRating: 'AAA' },
  { id: 'POL', type: 'country', label: 'Poland', countryCode: 'POL', gdp: 842e9, gdpGrowth: 0.2, population: 38e6, region: 'eastern_europe', currency: 'PLN', inflation: 6.2, unemployment: 5.1, debtToGdp: 49, interestRate: 5.75, creditRating: 'A-' },
  { id: 'SWE', type: 'country', label: 'Sweden', countryCode: 'SWE', gdp: 593e9, gdpGrowth: -0.1, population: 10e6, region: 'western_europe', currency: 'SEK', inflation: 2.3, unemployment: 7.5, debtToGdp: 31, interestRate: 4.00, creditRating: 'AAA' },
  { id: 'BEL', type: 'country', label: 'Belgium', countryCode: 'BEL', gdp: 624e9, gdpGrowth: 1.4, population: 12e6, region: 'western_europe', currency: 'EUR', inflation: 1.4, unemployment: 5.5, debtToGdp: 105, interestRate: 4.00, creditRating: 'AA-' },
  { id: 'NOR', type: 'country', label: 'Norway', countryCode: 'NOR', gdp: 485e9, gdpGrowth: 0.5, population: 5e6, region: 'western_europe', currency: 'NOK', inflation: 4.7, unemployment: 3.5, debtToGdp: 43, interestRate: 4.50, creditRating: 'AAA' },
  { id: 'AUT', type: 'country', label: 'Austria', countryCode: 'AUT', gdp: 516e9, gdpGrowth: -0.8, population: 9e6, region: 'western_europe', currency: 'EUR', inflation: 4.3, unemployment: 5.1, debtToGdp: 78, interestRate: 4.00, creditRating: 'AA+' },
  { id: 'ARE', type: 'country', label: 'UAE', countryCode: 'ARE', gdp: 509e9, gdpGrowth: 3.4, population: 10e6, region: 'middle_east', currency: 'AED', inflation: 2.3, unemployment: 2.9, debtToGdp: 30, interestRate: 5.40, creditRating: 'AA' },
  { id: 'ISR', type: 'country', label: 'Israel', countryCode: 'ISR', gdp: 525e9, gdpGrowth: 2.0, population: 10e6, region: 'middle_east', currency: 'ILS', inflation: 3.3, unemployment: 3.4, debtToGdp: 62, interestRate: 4.75, creditRating: 'A+' },
  { id: 'NGA', type: 'country', label: 'Nigeria', countryCode: 'NGA', gdp: 363e9, gdpGrowth: 2.9, population: 224e6, region: 'africa', currency: 'NGN', inflation: 28.9, unemployment: 5.0, debtToGdp: 38, interestRate: 18.75, creditRating: 'B-' },
  { id: 'THA', type: 'country', label: 'Thailand', countryCode: 'THA', gdp: 515e9, gdpGrowth: 1.9, population: 72e6, region: 'south_se_asia', currency: 'THB', inflation: 1.1, unemployment: 1.1, debtToGdp: 62, interestRate: 2.50, creditRating: 'BBB+' },
  { id: 'SGP', type: 'country', label: 'Singapore', countryCode: 'SGP', gdp: 497e9, gdpGrowth: 1.1, population: 6e6, region: 'south_se_asia', currency: 'SGD', inflation: 3.7, unemployment: 2.0, debtToGdp: 168, interestRate: 3.50, creditRating: 'AAA' },
  { id: 'PHL', type: 'country', label: 'Philippines', countryCode: 'PHL', gdp: 437e9, gdpGrowth: 5.6, population: 117e6, region: 'south_se_asia', currency: 'PHP', inflation: 4.1, unemployment: 4.3, debtToGdp: 61, interestRate: 6.50, creditRating: 'BBB+' },
  { id: 'MYS', type: 'country', label: 'Malaysia', countryCode: 'MYS', gdp: 400e9, gdpGrowth: 3.7, population: 34e6, region: 'south_se_asia', currency: 'MYR', inflation: 1.8, unemployment: 3.4, debtToGdp: 66, interestRate: 3.00, creditRating: 'A-' },
  { id: 'DNK', type: 'country', label: 'Denmark', countryCode: 'DNK', gdp: 404e9, gdpGrowth: 1.9, population: 6e6, region: 'western_europe', currency: 'DKK', inflation: 1.0, unemployment: 2.7, debtToGdp: 29, interestRate: 3.60, creditRating: 'AAA' },
  { id: 'IRL', type: 'country', label: 'Ireland', countryCode: 'IRL', gdp: 545e9, gdpGrowth: -3.2, population: 5e6, region: 'western_europe', currency: 'EUR', inflation: 2.8, unemployment: 4.3, debtToGdp: 44, interestRate: 4.00, creditRating: 'AA-' },
  { id: 'HKG', type: 'country', label: 'Hong Kong', countryCode: 'HKG', gdp: 383e9, gdpGrowth: 3.2, population: 7e6, region: 'east_asia', currency: 'HKD', inflation: 1.7, unemployment: 2.9, debtToGdp: 38, interestRate: 5.75, creditRating: 'AA+' },
  { id: 'COL', type: 'country', label: 'Colombia', countryCode: 'COL', gdp: 335e9, gdpGrowth: 0.6, population: 52e6, region: 'latin_america', currency: 'COP', inflation: 9.3, unemployment: 10.2, debtToGdp: 52, interestRate: 13.00, creditRating: 'BB+' },
  { id: 'ZAF', type: 'country', label: 'South Africa', countryCode: 'ZAF', gdp: 377e9, gdpGrowth: 0.7, population: 60e6, region: 'africa', currency: 'ZAR', inflation: 5.1, unemployment: 32.1, debtToGdp: 73, interestRate: 8.25, creditRating: 'BB-' },
  { id: 'EGY', type: 'country', label: 'Egypt', countryCode: 'EGY', gdp: 395e9, gdpGrowth: 3.8, population: 111e6, region: 'middle_east', currency: 'EGP', inflation: 33.7, unemployment: 7.0, debtToGdp: 92, interestRate: 19.25, creditRating: 'B-' },
  { id: 'CHL', type: 'country', label: 'Chile', countryCode: 'CHL', gdp: 335e9, gdpGrowth: 0.2, population: 20e6, region: 'latin_america', currency: 'CLP', inflation: 3.9, unemployment: 8.5, debtToGdp: 38, interestRate: 8.25, creditRating: 'A' },
  { id: 'FIN', type: 'country', label: 'Finland', countryCode: 'FIN', gdp: 300e9, gdpGrowth: -1.0, population: 6e6, region: 'western_europe', currency: 'EUR', inflation: 1.8, unemployment: 7.6, debtToGdp: 75, interestRate: 4.00, creditRating: 'AA+' },
  { id: 'VNM', type: 'country', label: 'Vietnam', countryCode: 'VNM', gdp: 430e9, gdpGrowth: 5.1, population: 100e6, region: 'south_se_asia', currency: 'VND', inflation: 3.6, unemployment: 2.3, debtToGdp: 37, interestRate: 4.50, creditRating: 'BB+' },
  { id: 'BGD', type: 'country', label: 'Bangladesh', countryCode: 'BGD', gdp: 460e9, gdpGrowth: 5.8, population: 173e6, region: 'south_se_asia', currency: 'BDT', inflation: 9.5, unemployment: 5.2, debtToGdp: 35, interestRate: 8.50, creditRating: 'BB-' },
  { id: 'ARG', type: 'country', label: 'Argentina', countryCode: 'ARG', gdp: 621e9, gdpGrowth: -1.6, population: 46e6, region: 'latin_america', currency: 'ARS', inflation: 211.4, unemployment: 6.2, debtToGdp: 85, interestRate: 100.00, creditRating: 'CCC-' },
  { id: 'PRT', type: 'country', label: 'Portugal', countryCode: 'PRT', gdp: 287e9, gdpGrowth: 2.3, population: 10e6, region: 'western_europe', currency: 'EUR', inflation: 2.3, unemployment: 6.5, debtToGdp: 112, interestRate: 4.00, creditRating: 'A-' },
  { id: 'NZL', type: 'country', label: 'New Zealand', countryCode: 'NZL', gdp: 252e9, gdpGrowth: 0.6, population: 5e6, region: 'oceania', currency: 'NZD', inflation: 4.7, unemployment: 3.9, debtToGdp: 53, interestRate: 5.50, creditRating: 'AAA' },
  { id: 'CZE', type: 'country', label: 'Czechia', countryCode: 'CZE', gdp: 330e9, gdpGrowth: -0.4, population: 11e6, region: 'eastern_europe', currency: 'CZK', inflation: 6.9, unemployment: 3.5, debtToGdp: 44, interestRate: 7.00, creditRating: 'AA-' },
  { id: 'QAT', type: 'country', label: 'Qatar', countryCode: 'QAT', gdp: 236e9, gdpGrowth: 1.6, population: 3e6, region: 'middle_east', currency: 'QAR', inflation: 2.4, unemployment: 0.1, debtToGdp: 42, interestRate: 6.00, creditRating: 'AA' },
  { id: 'KAZ', type: 'country', label: 'Kazakhstan', countryCode: 'KAZ', gdp: 261e9, gdpGrowth: 5.1, population: 20e6, region: 'eastern_europe', currency: 'KZT', inflation: 9.8, unemployment: 4.8, debtToGdp: 23, interestRate: 15.75, creditRating: 'BBB-' },
  { id: 'PER', type: 'country', label: 'Peru', countryCode: 'PER', gdp: 268e9, gdpGrowth: -0.6, population: 34e6, region: 'latin_america', currency: 'PEN', inflation: 3.2, unemployment: 6.7, debtToGdp: 33, interestRate: 7.25, creditRating: 'BBB' },
  { id: 'PAK', type: 'country', label: 'Pakistan', countryCode: 'PAK', gdp: 338e9, gdpGrowth: -0.2, population: 231e6, region: 'south_se_asia', currency: 'PKR', inflation: 28.3, unemployment: 6.3, debtToGdp: 75, interestRate: 22.00, creditRating: 'CCC+' },
]

// ── Major bilateral trade relationships ────────────────────────────────────────────

export const MOCK_TRADE_EDGES: EconEdge[] = [
  { id: 't1', source: 'USA', target: 'CHN', type: 'trade', weight: 1, value: 575e9, direction: 'bidirectional' },
  { id: 't2', source: 'USA', target: 'CAN', type: 'trade', weight: 0.9, value: 780e9, direction: 'bidirectional' },
  { id: 't3', source: 'USA', target: 'MEX', type: 'trade', weight: 0.85, value: 798e9, direction: 'bidirectional' },
  { id: 't4', source: 'USA', target: 'DEU', type: 'trade', weight: 0.6, value: 252e9, direction: 'bidirectional' },
  { id: 't5', source: 'USA', target: 'JPN', type: 'trade', weight: 0.55, value: 226e9, direction: 'bidirectional' },
  { id: 't6', source: 'USA', target: 'KOR', type: 'trade', weight: 0.5, value: 196e9, direction: 'bidirectional' },
  { id: 't7', source: 'USA', target: 'GBR', type: 'trade', weight: 0.45, value: 148e9, direction: 'bidirectional' },
  { id: 't8', source: 'USA', target: 'IND', type: 'trade', weight: 0.5, value: 191e9, direction: 'bidirectional' },
  { id: 't9', source: 'USA', target: 'TWN', type: 'trade', weight: 0.45, value: 127e9, direction: 'bidirectional' },
  { id: 't10', source: 'USA', target: 'BRA', type: 'trade', weight: 0.3, value: 92e9, direction: 'bidirectional' },
  { id: 't11', source: 'CHN', target: 'JPN', type: 'trade', weight: 0.65, value: 318e9, direction: 'bidirectional' },
  { id: 't12', source: 'CHN', target: 'KOR', type: 'trade', weight: 0.7, value: 362e9, direction: 'bidirectional' },
  { id: 't13', source: 'CHN', target: 'AUS', type: 'trade', weight: 0.55, value: 231e9, direction: 'bidirectional' },
  { id: 't14', source: 'CHN', target: 'DEU', type: 'trade', weight: 0.5, value: 210e9, direction: 'bidirectional' },
  { id: 't15', source: 'CHN', target: 'TWN', type: 'trade', weight: 0.55, value: 268e9, direction: 'bidirectional' },
  { id: 't16', source: 'CHN', target: 'BRA', type: 'trade', weight: 0.45, value: 181e9, direction: 'bidirectional' },
  { id: 't17', source: 'CHN', target: 'RUS', type: 'trade', weight: 0.4, value: 240e9, direction: 'bidirectional' },
  { id: 't18', source: 'CHN', target: 'SAU', type: 'trade', weight: 0.35, value: 106e9, direction: 'bidirectional' },
  { id: 't19', source: 'CHN', target: 'VNM', type: 'trade', weight: 0.4, value: 175e9, direction: 'bidirectional' },
  { id: 't20', source: 'CHN', target: 'MYS', type: 'trade', weight: 0.3, value: 98e9, direction: 'bidirectional' },
  { id: 't21', source: 'DEU', target: 'FRA', type: 'trade', weight: 0.65, value: 189e9, direction: 'bidirectional' },
  { id: 't22', source: 'DEU', target: 'NLD', type: 'trade', weight: 0.55, value: 172e9, direction: 'bidirectional' },
  { id: 't23', source: 'DEU', target: 'ITA', type: 'trade', weight: 0.45, value: 142e9, direction: 'bidirectional' },
  { id: 't24', source: 'DEU', target: 'POL', type: 'trade', weight: 0.4, value: 125e9, direction: 'bidirectional' },
  { id: 't25', source: 'DEU', target: 'CHE', type: 'trade', weight: 0.35, value: 98e9, direction: 'bidirectional' },
  { id: 't26', source: 'DEU', target: 'AUT', type: 'trade', weight: 0.3, value: 85e9, direction: 'bidirectional' },
  { id: 't27', source: 'FRA', target: 'ESP', type: 'trade', weight: 0.35, value: 95e9, direction: 'bidirectional' },
  { id: 't28', source: 'FRA', target: 'ITA', type: 'trade', weight: 0.35, value: 88e9, direction: 'bidirectional' },
  { id: 't29', source: 'FRA', target: 'BEL', type: 'trade', weight: 0.3, value: 82e9, direction: 'bidirectional' },
  { id: 't30', source: 'GBR', target: 'NLD', type: 'trade', weight: 0.3, value: 72e9, direction: 'bidirectional' },
  { id: 't31', source: 'JPN', target: 'KOR', type: 'trade', weight: 0.4, value: 82e9, direction: 'bidirectional' },
  { id: 't32', source: 'JPN', target: 'AUS', type: 'trade', weight: 0.35, value: 68e9, direction: 'bidirectional' },
  { id: 't33', source: 'JPN', target: 'TWN', type: 'trade', weight: 0.35, value: 75e9, direction: 'bidirectional' },
  { id: 't34', source: 'JPN', target: 'THA', type: 'trade', weight: 0.3, value: 55e9, direction: 'bidirectional' },
  { id: 't35', source: 'KOR', target: 'VNM', type: 'trade', weight: 0.3, value: 87e9, direction: 'bidirectional' },
  { id: 't36', source: 'SGP', target: 'MYS', type: 'trade', weight: 0.35, value: 65e9, direction: 'bidirectional' },
  { id: 't37', source: 'IND', target: 'ARE', type: 'trade', weight: 0.35, value: 85e9, direction: 'bidirectional' },
  { id: 't38', source: 'IND', target: 'SAU', type: 'trade', weight: 0.3, value: 52e9, direction: 'bidirectional' },
  { id: 't39', source: 'AUS', target: 'NZL', type: 'trade', weight: 0.2, value: 15e9, direction: 'bidirectional' },
  { id: 't40', source: 'BRA', target: 'ARG', type: 'trade', weight: 0.25, value: 28e9, direction: 'bidirectional' },
  { id: 't41', source: 'CAN', target: 'GBR', type: 'trade', weight: 0.2, value: 32e9, direction: 'bidirectional' },
  { id: 't42', source: 'MEX', target: 'CHN', type: 'trade', weight: 0.25, value: 45e9, direction: 'bidirectional' },
  { id: 't43', source: 'SAU', target: 'IND', type: 'trade', weight: 0.3, value: 52e9, direction: 'bidirectional' },
  { id: 't44', source: 'SAU', target: 'JPN', type: 'trade', weight: 0.25, value: 42e9, direction: 'bidirectional' },
  { id: 't45', source: 'ZAF', target: 'CHN', type: 'trade', weight: 0.2, value: 35e9, direction: 'bidirectional' },
  { id: 't46', source: 'NGA', target: 'IND', type: 'trade', weight: 0.15, value: 15e9, direction: 'bidirectional' },
  { id: 't47', source: 'RUS', target: 'CHN', type: 'trade', weight: 0.4, value: 240e9, direction: 'bidirectional' },
  { id: 't48', source: 'RUS', target: 'IND', type: 'trade', weight: 0.25, value: 65e9, direction: 'bidirectional' },
  { id: 't49', source: 'QAT', target: 'JPN', type: 'trade', weight: 0.15, value: 22e9, direction: 'bidirectional' },
  { id: 't50', source: 'QAT', target: 'KOR', type: 'trade', weight: 0.15, value: 18e9, direction: 'bidirectional' },
]

export const MOCK_FDI_EDGES: EconEdge[] = [
  { id: 'fdi1', source: 'USA', target: 'GBR', type: 'fdi', weight: 0.8, value: 851e9, direction: 'bidirectional' },
  { id: 'fdi2', source: 'USA', target: 'NLD', type: 'fdi', weight: 0.7, value: 565e9, direction: 'bidirectional' },
  { id: 'fdi3', source: 'USA', target: 'IRL', type: 'fdi', weight: 0.5, value: 375e9, direction: 'source_to_target' },
  { id: 'fdi4', source: 'USA', target: 'CAN', type: 'fdi', weight: 0.5, value: 425e9, direction: 'bidirectional' },
  { id: 'fdi5', source: 'JPN', target: 'USA', type: 'fdi', weight: 0.6, value: 721e9, direction: 'source_to_target' },
  { id: 'fdi6', source: 'DEU', target: 'USA', type: 'fdi', weight: 0.5, value: 482e9, direction: 'source_to_target' },
  { id: 'fdi7', source: 'CHN', target: 'USA', type: 'fdi', weight: 0.3, value: 38e9, direction: 'source_to_target' },
  { id: 'fdi8', source: 'SGP', target: 'CHN', type: 'fdi', weight: 0.3, value: 55e9, direction: 'source_to_target' },
  { id: 'fdi9', source: 'HKG', target: 'CHN', type: 'fdi', weight: 0.7, value: 102e9, direction: 'source_to_target' },
  { id: 'fdi10', source: 'USA', target: 'IND', type: 'fdi', weight: 0.3, value: 46e9, direction: 'source_to_target' },
]

export const MOCK_REMITTANCE_EDGES: EconEdge[] = [
  { id: 'rem1', source: 'USA', target: 'MEX', type: 'remittance', weight: 0.8, value: 63e9, direction: 'source_to_target' },
  { id: 'rem2', source: 'USA', target: 'IND', type: 'remittance', weight: 0.6, value: 28e9, direction: 'source_to_target' },
  { id: 'rem3', source: 'USA', target: 'PHL', type: 'remittance', weight: 0.5, value: 18e9, direction: 'source_to_target' },
  { id: 'rem4', source: 'SAU', target: 'IND', type: 'remittance', weight: 0.5, value: 21e9, direction: 'source_to_target' },
  { id: 'rem5', source: 'ARE', target: 'IND', type: 'remittance', weight: 0.4, value: 18e9, direction: 'source_to_target' },
  { id: 'rem6', source: 'SAU', target: 'PAK', type: 'remittance', weight: 0.3, value: 7e9, direction: 'source_to_target' },
  { id: 'rem7', source: 'SAU', target: 'EGY', type: 'remittance', weight: 0.3, value: 6e9, direction: 'source_to_target' },
  { id: 'rem8', source: 'SAU', target: 'BGD', type: 'remittance', weight: 0.3, value: 5e9, direction: 'source_to_target' },
  { id: 'rem9', source: 'USA', target: 'CHN', type: 'remittance', weight: 0.2, value: 5e9, direction: 'source_to_target' },
  { id: 'rem10', source: 'DEU', target: 'TUR', type: 'remittance', weight: 0.2, value: 3e9, direction: 'source_to_target' },
]

export const MOCK_STOCKS = [
  { symbol: 'SPY', name: 'S&P 500 ETF', price: 570.25, change: 0.42 },
  { symbol: 'QQQ', name: 'NASDAQ 100 ETF', price: 495.80, change: 0.65 },
  { symbol: 'DIA', name: 'Dow Jones ETF', price: 425.10, change: 0.18 },
  { symbol: 'AAPL', name: 'Apple', price: 227.45, change: -0.32 },
  { symbol: 'MSFT', name: 'Microsoft', price: 445.20, change: 0.88 },
  { symbol: 'NVDA', name: 'NVIDIA', price: 138.50, change: 2.15 },
  { symbol: 'GOOGL', name: 'Alphabet', price: 175.30, change: 0.45 },
  { symbol: 'AMZN', name: 'Amazon', price: 225.60, change: 1.12 },
  { symbol: 'META', name: 'Meta', price: 620.80, change: -0.55 },
  { symbol: 'TSLA', name: 'Tesla', price: 175.90, change: -1.85 },
  { symbol: 'FTSE', name: 'FTSE 100', price: 7850.00, change: 0.32 },
  { symbol: 'DAX', name: 'DAX 40', price: 18200.00, change: -0.15 },
  { symbol: 'N225', name: 'Nikkei 225', price: 38500.00, change: 0.85 },
  { symbol: 'HSI', name: 'Hang Seng', price: 17200.00, change: 1.25 },
  { symbol: 'SENSEX', name: 'BSE Sensex', price: 73500.00, change: 0.45 },
]

export const MOCK_CRYPTO = [
  { id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin', price: 87250, change24h: 2.3, marketCap: 1.71e12 },
  { id: 'ethereum', symbol: 'ETH', name: 'Ethereum', price: 3420, change24h: -0.8, marketCap: 412e9 },
  { id: 'solana', symbol: 'SOL', name: 'Solana', price: 185, change24h: 4.2, marketCap: 82e9 },
  { id: 'binancecoin', symbol: 'BNB', name: 'BNB', price: 625, change24h: 0.5, marketCap: 93e9 },
  { id: 'ripple', symbol: 'XRP', name: 'XRP', price: 2.45, change24h: -1.2, marketCap: 138e9 },
]

export const MOCK_YIELDS = {
  current: { '2Y': 4.28, '5Y': 4.05, '10Y': 4.25, '30Y': 4.48 },
  oneYearAgo: { '2Y': 4.72, '5Y': 4.25, '10Y': 4.32, '30Y': 4.50 },
  twoYearsAgo: { '2Y': 5.05, '5Y': 4.50, '10Y': 4.68, '30Y': 4.85 },
  fedFunds: 4.33,
  dollarIndex: 112.45,
}
